Vagrant.configure("2") do |config|
    config.vm.define "gNB" do |gnb|
      gnb.vm.box = "generic/ubuntu2004"
      gnb.vm.hostname = "gNB2"
      gnb.vm.network :private_network, ip: "192.168.200.5", libvirt__network_name: "net33"
      gnb.vm.provider :libvirt do |libvirt|
        libvirt.memory = 2048
        libvirt.cpus = 1
        libvirt.storage_pool_name = "vm"
      end
    end
  end