Vagrant.configure("2") do |config|
  config.vm.define "gNB" do |gnb|
    gnb.vm.box = "generic/ubuntu2004"
    gnb.vm.hostname = "gNB"
    gnb.vm.network :private_network, ip: "192.168.200.3", libvirt__network_name: "net33"
    gnb.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 1
      libvirt.storage_pool_name = "vm"
    end

    # gnb.vm.provision "file", source: "config-gnb.yaml", destination: "/home/vagrant/config/config-gnb.yaml"
    gnb.vm.provision "shell", path: "dependencies2.sh"
  end
end